[package]
name = "proj_euler"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "problem_1"

[[bin]]
name = "problem_2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
