[package]
name = "signal_handler"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
opt-level = 2

[dependencies]
signal-hook = "0.3.10"
