[package]
name = "call_from_c"
version = "0.1.0"
authors = ["Alexander Zoellner <zoellner.contact@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "call_from_c"
crate-type = ["staticlib"]

[dependencies]
